### DISCUSSION TITLE
How to migrate from Shorewall to Firewalld?

### DISCUSSION THREAD

**Discussion by MirtoBusico** [firewalld/firewalld#1215] [Q&A]
Hi all
I'm new to firewalld and I'm trying to replicate the functionalities I was used to set in Shorewall; but I'm confused and lost in the documentation.

I have a physical network lan card (enp39s0) with multiple fixed IP addresses: the first one is for the host and the others are used for NAT (from 192.168.1.10 to 192.168.1.16)

I have two virtual bridges managed by virtual manager: one used for MASQUERADE the virtual addresses to access Internet and the other to NAT fixed IP of Virtual Machines to addresses of the physical lan card.

Here the scheme
![mostro_rete](https://github.com/firewalld/firewalld/assets/11090934/78eae35a-c899-4420-b317-e93e26fcb179)

In shorewall I had to set two tables:

**snat** containing

```
MASQUERADE      192.168.102.0/24        enp39s0
```

and **nat** containing
```
#EXTERNAL       INTERFACE       INTERNAL        ALLINTS         LOCAL
192.168.1.11    enp39s0        192.168.100.11
```

Trying to do the same in firewalld I lost myself among zones, policies, rich rules etc.

How can I do MASQUERADE and NAT?

**Comment by MirtoBusico** [comment]
**Update**

With the default values for the "external" zone, assigning the enp39s0 to this zone
The zone says
```
mirto@ubumostro:~$ sudo firewall-cmd --zone=external --list-all
[sudo] password for mirto: 
external (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp1s0
  sources: 
  services: http http3 https ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
mirto@ubumostro:~$ 
```

 I see that

- the virbr1 network is masqueraded (OK)
- also the virbr3 network is masqueraded (this is not what I want - how can I disable this?)

Still I have no idea how to NAT 192.168.100.11 on 192.168.1.11
