### DISCUSSION TITLE
Blocking IPs before forwarding

### DISCUSSION THREAD

**Discussion by LaXiS96** [firewalld/firewalld#1322] [Q&A] [answered]
Hello,
I have Docker set up with manual port forwarding to static container IPs and I need to block external source IPs from an ipset.

Port forwards are configured with rich rules on the public-facing zone/interface.
I first tried by adding a `source` rich rule on the same zone, that would match on the ipset and then reject, but that doesn't seem to work.
I see that it results in an nftables rule in a zone FILTER chain, which AFAIK is not used for a forwarded packet.
Putting the reject rule on the `docker` zone is also useless, since this zone is not relevant to the forwarded packet.

I believe the solution would be to place the reject rule in a global PREROUTING chain (FILTER table on PREROUTING hook?), but which is the correct way to do so?

**Comment by erig0** [comment]
Can you share your config? AFAIUI, you have the "port forwards" configured via firewalld (and not via docker --publish).

Are you trying to block traffic that is already established, i.e. an existing connection?
Or are you trying to block a subset of the traffic that has been port forwarded?

**Reply by LaXiS96** [reply]
I just found one solution: adding the ipset as a source to the `block` zone. This ensures rules are set up for both local (in nft chain `filter_INPUT_ZONES`) and forwarded packets (in `filter_FORWARD_IN_ZONES`).

The other solution I was thinking about would have involved a policy, but I feel the `block` zone is better suited.

About my situation, this is how firewalld is setup (Docker's iptables integration is disabled and no ports are ever published):
```
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources:
  services: dhcpv6-client ssh wireguard
  ports:
  protocols:
  forward: no
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
        rule family="ipv4" forward-port port="80" protocol="tcp" to-addr="172.18.0.10"
```
Now say I want to block any packet (including TCP port 80) from IP 1.2.3.4, my first thought was to add a rich rule like this:
```sh
sudo firewall-cmd --permanent --new-ipset=block_ip --type=hash:ip
sudo firewall-cmd --permanent --ipset=block_ip --add-entry=1.2.3.4
sudo firewall-cmd --permanent --zone=public --add-rich-rule='rule family=ipv4 source ipset=block_ip reject'
sudo firewall-cmd --reload
```
but that would only have worked for non-forwarded packets (= not those for TCP port 80), since the reject rule is added to the `filter_IN_public_deny` chain only.

The correct way was instead:
```sh
sudo firewall-cmd --permanent --zone=block --add-source=ipset:block_ip
sudo firewall-cmd --reload
```

In this case the connection was HTTP spam, I tried force-closing it with `ss -K` and `conntrack -D` but the NAT mapping wasn't going away from `conntrack -L`. I believe each HTTP request was opening a new connection and since firewalld was not blocking it, a new `conntrack` entry was instantly added.

Thank you
