### DISCUSSION TITLE
How to close access from one zone to the interface of another zone?

### DISCUSSION THREAD

**Discussion by Singijeon** [firewalld/firewalld#1367] [Q&A]
I have few IP tunnel configurations on my server.
Example of zones configuration:
```
mine_external (active)
  target: DROP
  icmp-block-inversion: yes
  interfaces: ens3
  sources:
  services: mine_ovpn-1 mine_ovpn-2
  ports:
  protocols:
  forward: no
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

mine_ovpn-1 (active)
  target: %%REJECT%%
  icmp-block-inversion: yes
  interfaces: ovpn-1
  sources:
  services: dns
  ports:
  protocols:
  forward: no
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks: echo-request
  rich rules:

mine_ovpn-2 (active)
  target: %%REJECT%%
  icmp-block-inversion: yes
  interfaces: ovpn-2
  sources:
  services: dns
  ports:
  protocols:
  forward: no
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks: echo-request
  rich rules:
```
Example of policies configuration:
```
_ovpn-1_to_exernal (active)
  priority: -1
  target: ACCEPT
  ingress-zones: mine_ovpn-1
  egress-zones: mine_external
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

_ovpn-2_to_exernal (active)
  priority: -1
  target: ACCEPT
  ingress-zones: mine_ovpn-2
  egress-zones: mine_external
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```
All works fine but client of one tunnel can access (ping and dns request) both virtual interface:
```
ovpn-1: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1300 qdisc fq state UNKNOWN group default qlen 500
    link/none
    inet 10.8.0.1 peer 10.8.0.2/32 scope global ovpn-1
       valid_lft forever preferred_lft forever
ovpn-2: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq state UNKNOWN group default qlen 500
    link/none
    inet 10.9.0.1 peer 10.9.0.2/32 scope global ovpn-2
       valid_lft forever preferred_lft forever
```
How to close access for clients of one subnet (ex. 10.8.0.0/24) to other subnet interfaces  (ex. 10.9.0.1) in the best way?
