### DISCUSSION TITLE
Port forwarding captures outgoing connections from Docker container

### DISCUSSION THREAD

**Discussion by ChargedByte** [firewalld/firewalld#1390] [Q&A]
Hello,

I've set up filtering and port forwarding for Docker according to Eric's two excellent blog posts on the topic:
- https://firewalld.org/2020/09/policy-objects-filtering-container-and-vm-traffic
- https://firewalld.org/2024/04/strictly-filtering-docker-containers

I'm mostly pleased with the result, but I've encountered a problem when forwarding a port, which is also used for external connections.

I have an agent container that has a service on port `9001/tcp` and a server container which makes connections to multiple agent containers. I can connect to the agent from within the Docker network without issues. My preference would be to connect using the external network instead to allow moving the server if needed without a configuration change. To facilitate this I applied a port forwarding rule for the agent container but now all connections from the server container on the port are redirecting to the local agent.

I also tried a rich rule with port forwarding but excluding the Docker network from source addresses but this just resulted in the port forward working from external networks but not working at all from the container. 

Unfortunately, I'm out of ideas on what I need to change to make this work so I'm hoping someone here can help.

<details>
<summary>Screenshots</summary>

Without port forwarding:
![Screenshot 2024-09-22 220131](https://github.com/user-attachments/assets/9b24778b-0ad6-4bff-8e31-158352569d6f)
With port forwarding:
![Screenshot 2024-09-22 221101](https://github.com/user-attachments/assets/8fe979a1-8a07-4c64-9b8e-3629604c10a2)
</details>

<details>
<summary>Docker</summary>

```json
{
  "default-address-pools": [
    { "base": "172.17.0.0/16", "size": 16 },
    { "base": "172.18.0.0/16", "size": 24 }
  ],
  "iptables": false,
  "ip6tables": false
}
```
</details>

<details>
<summary>Firewalld</summary>

```
Zones:
docker (active)
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces:
  sources: 172.17.0.1/16 172.18.0.1/16
  services:
  ports:
  protocols:
  forward: no
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

Policies:
docker-forwarding
  priority: -1
  target: ACCEPT
  ingress-zones:
  egress-zones:
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

docker-host (active)
  priority: -1
  target: REJECT
  ingress-zones: docker
  egress-zones: HOST
  services: dhcp dns
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

docker-port-fwds (active)
  priority: -1
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: HOST
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
        port=9001:proto=tcp:toport=9001:toaddr=172.18.0.2
        port=9443:proto=tcp:toport=9443:toaddr=172.18.0.3
  source-ports:
  icmp-blocks:
  rich rules:

docker-world (active)
  priority: -1
  target: ACCEPT
  ingress-zones: docker
  egress-zones: ANY
  services:
  ports:
  protocols:
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```
</details>
