### DISCUSSION TITLE
Docker: access container from container by public  host-ip:port

### DISCUSSION THREAD

**Discussion by valq7711** [firewalld/firewalld#1465] [Q&A]
Hi!
I am following this guide https://firewalld.org/2024/04/strictly-filtering-docker-containers and I am getting weird stuff.

I have user-defined docker network:
`sudo docker network create --subnet=172.20.0.0/16 --gateway=172.20.0.1 n20`
added to docker zone (`sources: 172.20.0.1/16` - see bellow)

Create an nginx-container listening on port `8011`:
```
sudo docker run -itd --name=nx --net=n20 --ip=172.20.0.11 nginx &&
sudo docker exec nx bash -c 'echo "NX: Hi there!" > /usr/share/nginx/html/index.html && sed -ri "s/listen\s+80;$/listen 8011;/" /etc/nginx/conf.d/default.conf' &&
sudo docker restart nx
```

Create a forwarding policy from `public` and `docker` zones:
```
sudo firewall-cmd --permanent --new-policy inz &&
sudo firewall-cmd --permanent --policy inz --add-ingress-zone public &&
sudo firewall-cmd --permanent --policy inz --add-ingress-zone docker &&
sudo firewall-cmd --permanent --policy inz --add-egress-zone ANY &&
sudo firewall-cmd --permanent --policy inz --add-forward-port port=8011:proto=tcp:toaddr=172.20.0.11
sudo firewall-cmd --reload
```

Create a policy from `docker` to `ANY` to give the container internet access :
```
sudo firewall-cmd --permanent --new-policy dockerToWorld
sudo firewall-cmd --permanent --policy dockerToWorld --add-ingress-zone docker
sudo firewall-cmd --permanent --policy dockerToWorld --add-egress-zone ANY
sudo firewall-cmd --permanent --policy dockerToWorld --set-target ACCEPT
sudo firewall-cmd --permanent --policy dockerToWorld --add-masquerade
sudo firewall-cmd --reload
```

Everything seems to be going well! we can:
`http://<host-ip>:8011` - external access via browser
`sudo docker exec nx curl http://google.com` - internet access from container
`sudo docker exec nx curl http://<host-ip>:8011` - host access via host-ip:port from container

But
```
sudo docker exec nx curl http://google.com:8011
NX: Hi there!

sudo docker exec nx curl 1.2.3.4:8011
NX: Hi there!

```

**So the question is**: Why does the forwarding policy ignore the destination IP address and only consider the port?

Here is what I have:

```
$ sudo firewall-cmd --version
1.1.1
```
```
$ sudo firewall-cmd --get-active-zones
docker
  sources: 172.20.0.1/16
public
  interfaces: ens3
```
```
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens3
  sources:
  services: dhcpv6-client ssh
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

docker (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces:
  sources: 172.20.0.1/16
  services:
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```
```
$ cat /etc/docker/daemon.json
{
    "iptables": false
}

$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```
