### ISSUE TITLE
filter_FWD_internal_REJECT internal zone -> external zone traffic is filtered

### ISSUE THREAD

**Issue by mrbojangles3** [firewalld/firewalld#1015]
### What happened

I am setting up a simple router to masquerade traffic from my internal zone to my external zone.  
```
[root@srvr mrbojangles]# firewall-cmd --list-all --zone=external
external (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp3s0
  sources:
  services: 
  ports: 
  protocols: 
  forward: no
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
[root@srvr mrbojangles]# firewall-cmd --list-all --zone=internal
internal (active)
  target: default
  icmp-block-inversion: no
  interfaces: br0
  sources: 192.168.3.0/24
  services: FAHClient ciscoanyc dhcp dhcpv6-client dns https ipsec samba-client ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
On a host inside the `internal` zone (192.168.3.105) I can ping my hosts on my subnet, but cannot get to the wider internet, ie cannot ping 1.1.1.1 from 192.168.3.105. The logs indicate the traffic is filtered. I cannot find / do not know what is the correct way to allow interzone traffic. 

```Sep 06 10:48:26 srvr kernel: filter_FWD_internal_REJECT: IN=br0 OUT=enp3s0 MAC=0e:6a:46:85:36:bb:00:e0:4c:68:76:a9:08:00 SRC=192.168.3.105 DST=1.1.1.1 LEN=84 TOS=0x00 PREC=0x00 TTL=63 ID=42628 DF PROTO=ICMP TYPE=8 CODE=0 ID=21 SEQ=1 
Sep 06 10:48:28 srvr kernel: filter_FWD_internal_REJECT: IN=br0 OUT=enp3s0 MAC=0e:6a:46:85:36:bb:00:e0:4c:68:76:a9:08:00 SRC=192.168.3.105 DST=1.1.1.1 LEN=84 TOS=0x00 PREC=0x00 TTL=63 ID=43449 DF PROTO=ICMP TYPE=8 CODE=0 ID=21 SEQ=2 
```

### What you expected to happen

I would expect traffic to not be filtered. It is possible that I need additional configuration as this is a setup from Fedora 33. possibly predating the transition to the nft backend. 

### How to reproduce it (as minimally and precisely as possible)

one interface in zone external. one bridge interface in zone internal. a host is attached to the bridge interface and attempt to ping a public ip address. 

### Anything else we need to know?

I could be missing something in my configuration, a policy maybe? Also someone on stack exchange has a similar problem
https://unix.stackexchange.com/questions/708068/firewalld-internal-zone-rejected

### Firewalld Version

1.0.5

### Firewalld Backend

nftables

### Linux distribution

Fedora 36

### Linux kernel version

5.19.6-200.fc36.x86_64
