### ISSUE TITLE
deleting permanent configuration out-of-band causes in memory configuration to be out of sync with on-disk configuration

### ISSUE THREAD

**Issue by fanicolini** [firewalld/firewalld#1043]
### What happened

If you try to add a new rich rule, file <zone.xml> is not created under /etc/firewalld/zones folder and rule lost.

firewall-cmd --permanent --add-rich-rule "rule family=\"ipv4\" icmp-type name=\"echo-reply\" drop"

### What you expected to happen

File  /etc/firewalld/zones/<zone>.xml should be created and added the following lines:

  <rule family="ipv4">
    <icmp-type name="echo-reply"/>
    <drop/>
  </rule>

### How to reproduce it (as minimally and precisely as possible)

1. set default zone public
2. if present, remove  /etc/firewalld/zones/public.xml
3. run commnd: firewall-cmd --permanent --add-rich-rule "rule family=\"ipv4\" icmp-type name=\"echo-reply\" drop"
4. file /etc/firewalld/zones/public.xml is not created

### Firewalld Version

0.9.3

### Firewalld Backend

nftables

### Linux distribution

Red Hat Enterprise Linux 8.6

### Linux kernel version

4.18.0-372.26.1.el8_6.x86_64

**Comment by erig0** [comment]
Did you happen to get this message?
```
Warning: ALREADY_ENABLED: rule family=ipv4 icmp-type name=echo-reply drop
```

You're removing the config file out-of-band of firewalld. However, firewalld maintains an in memory version of the permanent configuration. This avoids having to parse the file every time.

When you add the rich rule a second time the in memory config is identical so you get the ALREADY_ENABLED warning above. Additionally the zone is not re-written on disk because it did not change as far as firewalld knows.

```
[root@vm-local-rhel9-2 ~]# ls -al /etc/firewalld/zones/public.xml
ls: cannot access '/etc/firewalld/zones/public.xml': No such file or directory
[root@vm-local-rhel9-2 ~]# firewall-cmd --permanent --list-all --zone public
public
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns ssh
  ports: 
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
        rule family="ipv4" icmp-type name="echo-reply" drop
```

If you remove the configuration file out-of-band, then you need to reload firewalld afterwards.
```
# rm /etc/firewalld/zones/public.xml
# firewall-cmd --reload
```
