### ISSUE TITLE
Active FTP no longer works (kernel 6.x removed automatic connection tracking helpers)

### ISSUE THREAD

**Issue by holger24** [firewalld/firewalld#1049]
As of kernel 6.x /proc/sys/net/netfilter/nf_conntrack_helper is removed and I am no longer able to do active FTP to a remote FTP server (vsftp). The server running the ftp client (wilhelm) and the server running the ftp server (jacob) have the same firewalld (1.2.0) settings:
```
firewall-cmd --get-active-zones
bond0
  interfaces: bond0
public
  interfaces: eno1 eno2 ens1f0np0 ens1f1np1 ibp196s0
trusted
  interfaces: bond2

firewall-cmd --zone=bond0 --list-all
bond0 (active)
  target: default
  icmp-block-inversion: no
  interfaces: bond0
  sources: 
  services: ftp http https smtp smtps ssh
  ports: 
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks:
```
I would think that all modules are loaded on both sides:
```
lsmod|grep ftp
nf_nat_ftp             20480  0
nf_conntrack_ftp       24576  3 nf_nat_ftp
nf_nat                 57344  2 nf_nat_ftp,nft_chain_nat
nf_conntrack          172032  4 nf_nat,nft_ct,nf_nat_ftp,nf_conntrack_ftp
```

Here the ftp session from wilhelm (192.168.10.21):
```
ftp jacob
Connected to jacob (192.168.10.20).
220 Welcome to grimm FTP service.
Name (jacob:user): ftpuser
331 Please specify the password.
Password:
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> dir
227 Entering Passive Mode (192,168,10,20,206,212).
150 Here comes the directory listing.
drwxr-xr-x    2 9257     15101        4096 Nov 09 14:28 data
226 Directory send OK.
ftp> passiv
Passive mode off.
ftp> dir
200 PORT command successful. Consider using PASV.
425 Failed to establish connection.
ftp> 
221 Goodbye.
```
So passive works. But disabling passiv the response from jacob hits the firewall of wilhelm:
`Nov 15 10:43:58 wilhelm  IN=bond0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=192.168.10.20 DST=192.168.10.21 LEN=60 TOS=00 PREC=0x00 TTL=64 ID=8092 DF PROTO=TCP SPT=20 DPT=38191 SEQ=2739133115 ACK=0 WINDOW=64240 SYN URGP=0 MARK=0`

Using a older kernel with /proc/sys/net/netfilter/nf_conntrack_helper set to 1 this works. So how can I set this up correctly with firewalld on a new kernel 6.x?

**Firewalld Version**
1.2.0

**Linux kernel version**
6.0.7

**Distribution**
AlmaLinux 9

**FTP server**
vsftpd 3.0.3 (with setting connect_from_port_20=YES)
