### ISSUE TITLE
Includes in services are not working in rich-rules

### ISSUE THREAD

**Issue by arouene** [firewalld/firewalld#1075]
### What happened

Service **samba-dc** includes **dns**, **kerberos**, ...

```
# firewall-cmd --info-service samba-dc
samba-dc
  ports: 135/tcp 389/udp 49152-65535/tcp 3268/tcp 3269/tcp
  protocols: 
  source-ports: 
  modules: 
  destination: 
  includes: dns kerberos kpasswd ldap ldaps samba
  helpers:
```

If I had the **samba-dc** service in a policy, DNS rule (which is included) is set

```
# firewall-cmd --policy v68 --add-service samba-dc
success
# nft list ruleset | grep 53
                tcp dport 53 ct state { new, untracked } accept
                udp dport 53 ct state { new, untracked } accept
                tcp dport 49152-65535 ct state { new, untracked } accept
```

But if instead I use a rich-rule, the included services are not set

```
# firewall-cmd --policy v68 --add-rich-rule='rule family="ipv4" destination address="10.21.1.72" service name="samba-dc" accept'
success
# nft list ruleset | grep 53
                ip daddr 10.21.1.72 tcp dport 49152-65535 ct state { new, untracked } accept
```

### What you expected to happen

I expect "included services" to be set with rich-rules like they are set with a simple --add-service.

### How to reproduce it (as minimally and precisely as possible)

firewall-cmd --new-policy v68 --permanent
firewall-cmd --add-ingress-zone vlan06 --permanent
firewall-cmd --add-egress-zone vlan08 --permanent
 firewall-cmd --policy v68 --add-rich-rule='rule family="ipv4" destination address="10.21.1.72" service name="samba-dc" accept' --permanent

firewall-cmd --reload

nft list ruleset | grep  ' 53 '

### Firewalld Version

1.1.1

### Firewalld Backend

nftables

### Linux distribution

AlmaLinux 9

### Linux kernel version

5.14.0-162.6.1.el9_1.x86_64
