### ISSUE TITLE
[Feature Request] Specify path for `--check-config` switch

### ISSUE THREAD

**Issue by lonix1** [firewalld/firewalld#1126]
### What would you like to be added

There is the `--check-config` switch, to validate that the config is correct. It's very useful, and saved me much frustration.

However it doesn't seem to work well with something like ansible's [lineinfile module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html). Consider this:
````yml
- name: config firewalld
  become: true
  ansible.builtin.lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: "^#?FirewallBackend"
    line: "FirewallBackend=iptables"
    state: present
    validate: firewall-cmd --check-config         # <--------------
````

Ansible will report this error:
> validate must contain %s: firewall-cmd --check-config

That's because it places the updated config file in a temporary path `%s`, and points the validation tool to that path. But from [the docs](https://firewalld.org/documentation/man-pages/firewall-cmd.html#status_options) it seems firewalld looks in the default path and there's no way to change that.

Please consider adding an option for `--check-config`, so we can specify a path? For example `firewall-cmd --check-config /tmp/foo/firewalld.conf`. Then in ansible we could use `validate: firewall-cmd --check-config %s`.

I'm hoping that because firewalld and ansible both fall under the Red Hat umbrella, you'd consider this nice crossover feature request.

### Why is this needed

It would make automated provisioning of firewalld much easier.
