### ISSUE TITLE
Policy not applied to certain interface, behavior change or bug?

### ISSUE THREAD

**Issue by karuboniru** [firewalld/firewalld#1229]
### What happened

After upgrading to Fedora 39, my lan to wan forwarding stopped working. The exact setup was working when on Fedora 38 ([firewalld-1.3.4-1.fc38](https://koji.fedoraproject.org/koji/search?terms=firewalld-1.3.4-1.fc38&type=build&match=exact)) but stopped working now ([firewalld-2.0.1-1.fc39](https://koji.fedoraproject.org/koji/search?terms=firewalld-2.0.1-1.fc39&type=build&match=exact)).

My previous setup is that interface wgcf connects to WAN and assigned to zone public, several interfaces assigned to zone FedoraServer. A policy would allow any traffic to forward from lan (br0) to any interface. 

I tried to manually specify zones, the forward worked again.

```
> sudo firewall-cmd --info-policy=accept-lan-forward
accept-lan-forward (active)
  priority: -1
  target: ACCEPT
  ingress-zones: internal
  egress-zones: ANY
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule tcp-mss-clamp value="pmtu"
```

```
internal (active)
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: br0 cni-podman0 wg-server
  sources: 100.64.0.0/10
  services: dhcp dhcpv6 dhcpv6-client dns http https iscsi-target mdns mountd nfs ntp rpc-bind samba samba-client socks5 ssh tftp
  ports: 25555/udp
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

```
FedoraServer (default, active)
  target: DROP
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: board-p0 x540-hp-p0
  sources: 
  services: dhcpv6-client http http3 https ssh
  ports: 25555/udp
  protocols: 
  forward: no
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule family="ipv6" port port="29253" protocol="tcp" accept
	rule family="ipv6" source address="fc00::/7" masquerade
	rule family="ipv6" port port="29253" protocol="udp" accept
```

```
public (active)
  target: DROP
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: wgcf
  sources: 
  services: dhcpv6-client mdns ssh
  ports: 29253/udp 29253/tcp
  protocols: 
  forward: no
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule family="ipv6" source address="fc00::/7" masquerade
```

### What you expected to happen

The policy would allow forward to happen from internal to all interfaces.

### How to reproduce it (as minimally and precisely as possible)

Always

### Anything else we need to know?

The forward related chain is like below: you can see the rule applying `filter_FWD_policy_accept-lan-forward` to br0->wgcf is missing indicating that zone public is somehow missing from `egress-zones: ANY`.
```
	chain filter_FORWARD_POLICIES {
		ip saddr 100.64.0.0/10 ip daddr 100.64.0.0/10 jump filter_FWD_policy_accept-lan-forward
		ip saddr 100.64.0.0/10 ip daddr 100.64.0.0/10 jump filter_FWD_internal
		ip saddr 100.64.0.0/10 ip daddr 100.64.0.0/10 reject with icmpx admin-prohibited
		oifname "board-p0" ip saddr 100.64.0.0/10 jump filter_FWD_internal
		oifname "board-p0" ip saddr 100.64.0.0/10 reject with icmpx admin-prohibited
		oifname "x540-hp-p0" ip saddr 100.64.0.0/10 jump filter_FWD_internal
		oifname "x540-hp-p0" ip saddr 100.64.0.0/10 reject with icmpx admin-prohibited
		oifname "br0" ip saddr 100.64.0.0/10 jump filter_FWD_policy_accept-lan-forward
		oifname "br0" ip saddr 100.64.0.0/10 jump filter_FWD_internal
		oifname "br0" ip saddr 100.64.0.0/10 reject with icmpx admin-prohibited
		oifname "cni-podman0" ip saddr 100.64.0.0/10 jump filter_FWD_policy_accept-lan-forward
		oifname "cni-podman0" ip saddr 100.64.0.0/10 jump filter_FWD_internal
		oifname "cni-podman0" ip saddr 100.64.0.0/10 reject with icmpx admin-prohibited
		oifname "wg-server" ip saddr 100.64.0.0/10 jump filter_FWD_policy_accept-lan-forward
		oifname "wg-server" ip saddr 100.64.0.0/10 jump filter_FWD_internal
		oifname "wg-server" ip saddr 100.64.0.0/10 reject with icmpx admin-prohibited
		oifname "wgcf" ip saddr 100.64.0.0/10 jump filter_FWD_internal
		oifname "wgcf" ip saddr 100.64.0.0/10 reject with icmpx admin-prohibited
		ip saddr 100.64.0.0/10 jump filter_FWD_policy_accept-lan-forward
		ip saddr 100.64.0.0/10 jump filter_FWD_internal
		ip saddr 100.64.0.0/10 reject with icmpx admin-prohibited
		iifname "board-p0" ip daddr 100.64.0.0/10 jump filter_FWD_FedoraServer
		iifname "board-p0" ip daddr 100.64.0.0/10 drop
		iifname "board-p0" oifname "board-p0" jump filter_FWD_FedoraServer
		iifname "board-p0" oifname "board-p0" drop
		iifname "board-p0" oifname "x540-hp-p0" jump filter_FWD_FedoraServer
		iifname "board-p0" oifname "x540-hp-p0" drop
		iifname "board-p0" oifname "br0" jump filter_FWD_FedoraServer
		iifname "board-p0" oifname "br0" drop
		iifname "board-p0" oifname "cni-podman0" jump filter_FWD_FedoraServer
		iifname "board-p0" oifname "cni-podman0" drop
		iifname "board-p0" oifname "wg-server" jump filter_FWD_FedoraServer
		iifname "board-p0" oifname "wg-server" drop
		iifname "board-p0" oifname "wgcf" jump filter_FWD_FedoraServer
		iifname "board-p0" oifname "wgcf" drop
		iifname "board-p0" jump filter_FWD_FedoraServer
		iifname "board-p0" drop
		iifname "x540-hp-p0" ip daddr 100.64.0.0/10 jump filter_FWD_FedoraServer
		iifname "x540-hp-p0" ip daddr 100.64.0.0/10 drop
		iifname "x540-hp-p0" oifname "board-p0" jump filter_FWD_FedoraServer
		iifname "x540-hp-p0" oifname "board-p0" drop
		iifname "x540-hp-p0" oifname "x540-hp-p0" jump filter_FWD_FedoraServer
		iifname "x540-hp-p0" oifname "x540-hp-p0" drop
		iifname "x540-hp-p0" oifname "br0" jump filter_FWD_FedoraServer
		iifname "x540-hp-p0" oifname "br0" drop
		iifname "x540-hp-p0" oifname "cni-podman0" jump filter_FWD_FedoraServer
		iifname "x540-hp-p0" oifname "cni-podman0" drop
		iifname "x540-hp-p0" oifname "wg-server" jump filter_FWD_FedoraServer
		iifname "x540-hp-p0" oifname "wg-server" drop
		iifname "x540-hp-p0" oifname "wgcf" jump filter_FWD_FedoraServer
		iifname "x540-hp-p0" oifname "wgcf" drop
		iifname "x540-hp-p0" jump filter_FWD_FedoraServer
		iifname "x540-hp-p0" drop
		iifname "br0" ip daddr 100.64.0.0/10 jump filter_FWD_policy_accept-lan-forward
		iifname "br0" ip daddr 100.64.0.0/10 jump filter_FWD_internal
		iifname "br0" ip daddr 100.64.0.0/10 reject with icmpx admin-prohibited
		iifname "br0" oifname "board-p0" jump filter_FWD_policy_accept-lan-forward
		iifname "br0" oifname "board-p0" jump filter_FWD_internal
		iifname "br0" oifname "board-p0" reject with icmpx admin-prohibited
		iifname "br0" oifname "x540-hp-p0" jump filter_FWD_policy_accept-lan-forward
		iifname "br0" oifname "x540-hp-p0" jump filter_FWD_internal
		iifname "br0" oifname "x540-hp-p0" reject with icmpx admin-prohibited
		iifname "br0" oifname "br0" jump filter_FWD_internal
		iifname "br0" oifname "br0" reject with icmpx admin-prohibited
		iifname "br0" oifname "cni-podman0" jump filter_FWD_policy_accept-lan-forward
		iifname "br0" oifname "cni-podman0" jump filter_FWD_internal
		iifname "br0" oifname "cni-podman0" reject with icmpx admin-prohibited
		iifname "br0" oifname "wg-server" jump filter_FWD_policy_accept-lan-forward
		iifname "br0" oifname "wg-server" jump filter_FWD_internal
		iifname "br0" oifname "wg-server" reject with icmpx admin-prohibited
		iifname "br0" oifname "wgcf" jump filter_FWD_internal
		iifname "br0" oifname "wgcf" reject with icmpx admin-prohibited
		iifname "br0" jump filter_FWD_policy_accept-lan-forward
		iifname "br0" jump filter_FWD_internal
		iifname "br0" reject with icmpx admin-prohibited
		iifname "cni-podman0" ip daddr 100.64.0.0/10 jump filter_FWD_policy_accept-lan-forward
		iifname "cni-podman0" ip daddr 100.64.0.0/10 jump filter_FWD_internal
		iifname "cni-podman0" ip daddr 100.64.0.0/10 reject with icmpx admin-prohibited
		iifname "cni-podman0" oifname "board-p0" jump filter_FWD_policy_accept-lan-forward
		iifname "cni-podman0" oifname "board-p0" jump filter_FWD_internal
		iifname "cni-podman0" oifname "board-p0" reject with icmpx admin-prohibited
		iifname "cni-podman0" oifname "x540-hp-p0" jump filter_FWD_policy_accept-lan-forward
		iifname "cni-podman0" oifname "x540-hp-p0" jump filter_FWD_internal
		iifname "cni-podman0" oifname "x540-hp-p0" reject with icmpx admin-prohibited
		iifname "cni-podman0" oifname "br0" jump filter_FWD_policy_accept-lan-forward
		iifname "cni-podman0" oifname "br0" jump filter_FWD_internal
		iifname "cni-podman0" oifname "br0" reject with icmpx admin-prohibited
		iifname "cni-podman0" oifname "cni-podman0" jump filter_FWD_internal
		iifname "cni-podman0" oifname "cni-podman0" reject with icmpx admin-prohibited
		iifname "cni-podman0" oifname "wg-server" jump filter_FWD_policy_accept-lan-forward
		iifname "cni-podman0" oifname "wg-server" jump filter_FWD_internal
		iifname "cni-podman0" oifname "wg-server" reject with icmpx admin-prohibited
		iifname "cni-podman0" oifname "wgcf" jump filter_FWD_internal
		iifname "cni-podman0" oifname "wgcf" reject with icmpx admin-prohibited
		iifname "cni-podman0" jump filter_FWD_policy_accept-lan-forward
		iifname "cni-podman0" jump filter_FWD_internal
		iifname "cni-podman0" reject with icmpx admin-prohibited
		iifname "wg-server" ip daddr 100.64.0.0/10 jump filter_FWD_policy_accept-lan-forward
		iifname "wg-server" ip daddr 100.64.0.0/10 jump filter_FWD_internal
		iifname "wg-server" ip daddr 100.64.0.0/10 reject with icmpx admin-prohibited
		iifname "wg-server" oifname "board-p0" jump filter_FWD_policy_accept-lan-forward
		iifname "wg-server" oifname "board-p0" jump filter_FWD_internal
		iifname "wg-server" oifname "board-p0" reject with icmpx admin-prohibited
		iifname "wg-server" oifname "x540-hp-p0" jump filter_FWD_policy_accept-lan-forward
		iifname "wg-server" oifname "x540-hp-p0" jump filter_FWD_internal
		iifname "wg-server" oifname "x540-hp-p0" reject with icmpx admin-prohibited
		iifname "wg-server" oifname "br0" jump filter_FWD_policy_accept-lan-forward
		iifname "wg-server" oifname "br0" jump filter_FWD_internal
		iifname "wg-server" oifname "br0" reject with icmpx admin-prohibited
		iifname "wg-server" oifname "cni-podman0" jump filter_FWD_policy_accept-lan-forward
		iifname "wg-server" oifname "cni-podman0" jump filter_FWD_internal
		iifname "wg-server" oifname "cni-podman0" reject with icmpx admin-prohibited
		iifname "wg-server" oifname "wg-server" jump filter_FWD_internal
		iifname "wg-server" oifname "wg-server" reject with icmpx admin-prohibited
		iifname "wg-server" oifname "wgcf" jump filter_FWD_policy_accept-lan-forward
		iifname "wg-server" oifname "wgcf" jump filter_FWD_internal
		iifname "wg-server" oifname "wgcf" reject with icmpx admin-prohibited
		iifname "wg-server" jump filter_FWD_policy_accept-lan-forward
		iifname "wg-server" jump filter_FWD_internal
		iifname "wg-server" reject with icmpx admin-prohibited
		iifname "wgcf" ip daddr 100.64.0.0/10 jump filter_FWD_public
		iifname "wgcf" ip daddr 100.64.0.0/10 drop
		iifname "wgcf" oifname "board-p0" jump filter_FWD_public
		iifname "wgcf" oifname "board-p0" drop
		iifname "wgcf" oifname "x540-hp-p0" jump filter_FWD_public
		iifname "wgcf" oifname "x540-hp-p0" drop
		iifname "wgcf" oifname "br0" jump filter_FWD_public
		iifname "wgcf" oifname "br0" drop
		iifname "wgcf" oifname "cni-podman0" jump filter_FWD_public
		iifname "wgcf" oifname "cni-podman0" drop
		iifname "wgcf" oifname "wg-server" jump filter_FWD_public
		iifname "wgcf" oifname "wg-server" drop
		iifname "wgcf" oifname "wgcf" jump filter_FWD_public
		iifname "wgcf" oifname "wgcf" drop
		iifname "wgcf" jump filter_FWD_public
		iifname "wgcf" drop
		ip daddr 100.64.0.0/10 jump filter_FWD_FedoraServer
		ip daddr 100.64.0.0/10 drop
		oifname "board-p0" jump filter_FWD_FedoraServer
		oifname "board-p0" drop
		oifname "x540-hp-p0" jump filter_FWD_FedoraServer
		oifname "x540-hp-p0" drop
		oifname "br0" jump filter_FWD_FedoraServer
		oifname "br0" drop
		oifname "cni-podman0" jump filter_FWD_FedoraServer
		oifname "cni-podman0" drop
		oifname "wg-server" jump filter_FWD_FedoraServer
		oifname "wg-server" drop
		oifname "wgcf" jump filter_FWD_FedoraServer
		oifname "wgcf" drop
		jump filter_FWD_FedoraServer
		drop
	}
```

### Firewalld Version

2.0.1

### Firewalld Backend

nftables

### Linux distribution

Fedora 39

### Linux kernel version

6.5.6-300.fc39.x86_64
