### ISSUE TITLE
Add port forwarding to firewalld doesn't take effect actually

### ISSUE THREAD

**Issue by Silvigarabis** [firewalld/firewalld#1298]
### What happened

I added some port forward setting to firewalld, but it has no effect.

### What you expected to happen

Just make it work.

### How to reproduce it (as minimally and precisely as possible)

(I tried to minimal it, but I also need to list all possible I tested)

1. I tried to search the Internet for solutions, some one said I need to change the `net.ipv4.ip_forward` to `1`, and I did, but not work.
2. I have tried these command, but still not work.
```
firewall-cmd --add-masquerade --permanent
firewall-cmd --add-forward --permanent
firewall-cmd --reload
firewall-cmd --complete-reload
systemctl restart firewalld
apt upgrade -y
reboot
```
3. I also tried to configure with rich rule or firewalld policy, but still.
  - with directly add port forward to zone or policy 
```
# firewall-cmd --list-all
public (default, active)
  target: ACCEPT
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: lo
  sources:
  services: dhcp dhcpv6-client imc-frps murmur
  ports: 40280/tcp 23333/udp 15538/tcp 19106/tcp 15537/tcp 19105/tcp
  protocols:
  forward: yes
  masquerade: yes
  forward-ports:
        port=19105:proto=tcp:toport=15537:toaddr=127.0.0.1
  source-ports:
  icmp-blocks:
  rich rules:
        rule source NOT ipset="china_ipv4_address" port port="19107" protocol="tcp" reject

# firewall-cmd --list-all-policies
allow-host-ipv6 (active)
  priority: -15000
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: HOST
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
        rule family="ipv6" icmp-type name="neighbour-advertisement" accept
        rule family="ipv6" icmp-type name="neighbour-solicitation" accept
        rule family="ipv6" icmp-type name="router-advertisement" accept
        rule family="ipv6" icmp-type name="redirect" accept

internal-access (active)
  priority: -1
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: HOST
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
        rule source ipset="china_ipv4_address" service name="ssh" accept
        rule source ipset="china_ipv6_address" service name="ssh" accept
        rule source ipset="china_ipv6_address" service name="cockpit" accept
        rule source ipset="china_ipv4_address" port port="40022" protocol="tcp" accept
        rule source ipset="china_ipv6_address" port port="40022" protocol="tcp" accept
        rule family="ipv4" source address="172.16.0.1" log level="warning" limit value="5/m" accept

port-forwards (active)
  priority: -1
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: ANY
  services:
  ports: 15538/tcp 15537/tcp 19105/tcp 19106/tcp
  protocols:
  masquerade: yes
  forward-ports:
        port=19105:proto=tcp:toport=15537:toaddr=127.0.0.1
  source-ports:
  icmp-blocks:
  rich rules:
```
  - with rich rule configure
```
# firewall-cmd --list-all
public (default, active)
  target: ACCEPT
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: lo
  sources:
  services: dhcp dhcpv6-client imc-frps murmur
  ports: 40280/tcp 23333/udp 15538/tcp 19106/tcp 15537/tcp 19105/tcp
  protocols:
  forward: yes
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
        rule source NOT ipset="china_ipv4_address" port port="19107" protocol="tcp" reject
        rule family="ipv4" forward-port port="19105" protocol="tcp" to-port="15537" to-addr="127.0.0.1"

# firewall-cmd --list-all-policies
allow-host-ipv6 (active)
  priority: -15000
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: HOST
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
        rule family="ipv6" icmp-type name="neighbour-advertisement" accept
        rule family="ipv6" icmp-type name="neighbour-solicitation" accept
        rule family="ipv6" icmp-type name="router-advertisement" accept
        rule family="ipv6" icmp-type name="redirect" accept

internal-access (active)
  priority: -1
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: HOST
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
        rule source ipset="china_ipv4_address" service name="ssh" accept
        rule source ipset="china_ipv6_address" service name="ssh" accept
        rule source ipset="china_ipv6_address" service name="cockpit" accept
        rule source ipset="china_ipv4_address" port port="40022" protocol="tcp" accept
        rule source ipset="china_ipv6_address" port port="40022" protocol="tcp" accept
        rule family="ipv4" source address="172.16.0.1" log level="warning" limit value="5/m" accept

port-forwards (active)
  priority: -1
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: ANY
  services:
  ports: 15538/tcp 15537/tcp 19105/tcp 19106/tcp
  protocols:
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
        rule family="ipv4" forward-port port="19105" protocol="tcp" to-port="15537" to-addr="127.0.0.1"
```

after steps above, run some test code with `ncat`, or others can check it.
1. listen to the port
```
# ncat -vkl 15537
Ncat: Version 7.94SVN ( https://nmap.org/ncat )
Ncat: Listening on [::]:15537
Ncat: Listening on 0.0.0.0:15537
```
2. connect to source port, succeed
```
# ncat -v 127.0.0.1 15537
Ncat: Version 7.94SVN ( https://nmap.org/ncat )
Ncat: Connected to 127.0.0.1:15537.
<ctrl-d>Ncat: 0 bytes sent, 0 bytes received in 2.16 seconds.
```
  - and the listener will said
```
Ncat: Connection from 127.0.0.1:54474.
```
3. connect to forwarding port, failed
```
# ncat -v 127.0.0.1 19105
Ncat: Version 7.94SVN ( https://nmap.org/ncat )
Ncat: Connection refused.
```
  - and the listener will not say

### Anything else we need to know?

If you need, I can give the access of this machine to you, for finding the problem with it (but this is a VPS, not an real machine, above I need it to serve something, so you can only check the system).

I experienced this problem from I just touch the firewalld (about 1 year ago, I didn't say a lie), sometime I even thought whether there's a switch that I didn't on, but I didn't found.

The same problem alse appeared in another machine that I am managing, it's a real machine on regular firmware. But that's not mine, so I can only provide its system info:
```
$ cat /etc/os-release
PRETTY_NAME="Fedora Linux 38 (Server Edition)"

$ uname -a
Linux USTC 6.6.2-101.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov 22 21:31:13 UTC 2023 x86_64 GNU/Linux

$ LANG=C dnf info firewalld
Not root, Subscription Management repositories not updated
Last metadata expiration check: 0:24:17 ago on Sun Feb  4 13:14:41 2024.
Installed Packages
Name         : firewalld
Version      : 1.3.4
Release      : 1.fc38
Architecture : noarch
Size         : 2.1 M
Source       : firewalld-1.3.4-1.fc38.src.rpm
Repository   : @System
From repo    : updates
Summary      : A firewall daemon with D-Bus interface providing a dynamic firewall
URL          : http://www.firewalld.org
License      : GPLv2+
Description  : firewalld is a firewall service daemon that provides a dynamic
             : customizable firewall with a D-Bus interface.
```

### Firewalld Version

2.1.0-1

### Firewalld Backend

FirewallBackend=nftables

### Linux distribution

PRETTY_NAME="Debian GNU/Linux trixie/sid"

### Linux kernel version

6.6.13-cloud-amd64

### Other information

Some info
And *firewalld-debug-10.txt* from `firewalld --nofork --debug 10`: https://mclo.gs/nITlnF2

```
# uname -a
Linux imeaces 6.6.13-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.13-1 (2024-01-20) x86_64 GNU/Linux

# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux trixie/sid
Release:        n/a
Codename:       trixie

# sysctl -a |grep forward |grep 4                       net.ipv4.conf.all.bc_forwarding = 0
net.ipv4.conf.all.forwarding = 1                                      net.ipv4.conf.all.mc_forwarding = 0                                   net.ipv4.conf.default.bc_forwarding = 0
net.ipv4.conf.default.forwarding = 1
net.ipv4.conf.default.mc_forwarding = 0
net.ipv4.conf.eth0.bc_forwarding = 0
net.ipv4.conf.eth0.forwarding = 1
net.ipv4.conf.eth0.mc_forwarding = 0
net.ipv4.conf.he-ipv6.bc_forwarding = 0
net.ipv4.conf.he-ipv6.forwarding = 1
net.ipv4.conf.he-ipv6.mc_forwarding = 0
net.ipv4.conf.lo.bc_forwarding = 0
net.ipv4.conf.lo.forwarding = 1
net.ipv4.conf.lo.mc_forwarding = 0
net.ipv4.conf.sit0.bc_forwarding = 0
net.ipv4.conf.sit0.forwarding = 1
net.ipv4.conf.sit0.mc_forwarding = 0
.net.ipv4.ip_forward = 1
net.ipv4.ip_forward_update_priority = 1
net.ipv4.ip_forward_use_pmtu = 0

# firewall-cmd --get-default-zone
public

# firewall-cmd --list-all-zones
block
  target: %%REJECT%%
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

dmz
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

drop
  target: DROP
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: yes
  interfaces: 
  sources: 
  services: murmur
  ports: 
  protocols: 
  forward: yes
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: echo-reply echo-request
  rich rules: 

external
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: cockpit imc-frps murmur ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

home
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns samba-client ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

internal
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns samba-client ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

nm-shared
  target: ACCEPT
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcp dns ssh
  ports: 
  protocols: icmp ipv6-icmp
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule priority="32767" reject

public (default, active)
  target: ACCEPT
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: lo
  sources: 
  services: dhcp dhcpv6-client imc-frps murmur
  ports: 40280/tcp 23333/udp 15538/tcp 19106/tcp 15537/tcp 19105/tcp
  protocols: 
  forward: yes
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule source NOT ipset="china_ipv4_address" port port="19107" protocol="tcp" reject
	rule family="ipv4" forward-port port="19105" protocol="tcp" to-port="15537" to-addr="127.0.0.1"

trusted
  target: ACCEPT
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

work
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

# firewall-cmd --list-all-policies
allow-host-ipv6 (active)
  priority: -15000
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: HOST
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule family="ipv6" icmp-type name="neighbour-advertisement" accept
	rule family="ipv6" icmp-type name="neighbour-solicitation" accept
	rule family="ipv6" icmp-type name="router-advertisement" accept
	rule family="ipv6" icmp-type name="redirect" accept

internal-access (active)
  priority: -1
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: HOST
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule source ipset="china_ipv4_address" service name="ssh" accept
	rule source ipset="china_ipv6_address" service name="ssh" accept
	rule source ipset="china_ipv6_address" service name="cockpit" accept
	rule source ipset="china_ipv4_address" port port="40022" protocol="tcp" accept
	rule source ipset="china_ipv6_address" port port="40022" protocol="tcp" accept
	rule family="ipv4" source address="172.16.0.1" log level="warning" limit value="5/m" accept

port-forwards (active)
  priority: -1
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: ANY
  services: 
  ports: 15538/tcp 15537/tcp 19105/tcp 19106/tcp
  protocols: 
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule family="ipv4" forward-port port="19105" protocol="tcp" to-port="15537" to-addr="127.0.0.1"
```

full `/etc/firewalld/firewalld.conf`
```
# firewalld config file

# default zone
# The default zone used if an empty zone string is used.
# Default: public
DefaultZone=public

# Clean up on exit
# If set to no or false the firewall configuration will not get cleaned up
# on exit or stop of firewalld.
# Default: yes
CleanupOnExit=yes

# Clean up kernel modules on exit
# If set to yes or true the firewall related kernel modules will be
# unloaded on exit or stop of firewalld. This might attempt to unload
# modules not originally loaded by firewalld.
# Default: no
CleanupModulesOnExit=no

# Lockdown
# If set to enabled, firewall changes with the D-Bus interface will be limited
# to applications that are listed in the lockdown whitelist.
# The lockdown whitelist file is lockdown-whitelist.xml
# Default: no
Lockdown=no

# IPv6_rpfilter
# Performs a reverse path filter test on a packet for IPv6. If a reply to the
# packet would be sent via the same interface that the packet arrived on, the
# packet will match and be accepted, otherwise dropped.
# The rp_filter for IPv4 is controlled using sysctl.
# Note: This feature has a performance impact. See man page FIREWALLD.CONF(5)
# for details.
# Default: yes
IPv6_rpfilter=yes

# IndividualCalls
# Do not use combined -restore calls, but individual calls. This increases the
# time that is needed to apply changes and to start the daemon, but is good for
# debugging.
# Default: no
IndividualCalls=no

# LogDenied
# Add logging rules right before reject and drop rules in the INPUT, FORWARD
# and OUTPUT chains for the default rules and also final reject and drop rules
# in zones. Possible values are: all, unicast, broadcast, multicast and off.
# Default: off
LogDenied=off

# FirewallBackend
# Selects the firewall backend implementation.
# Choices are:
#	- nftables (default)
#	- iptables (iptables, ip6tables, ebtables and ipset)
# Note: The iptables backend is deprecated. It will be removed in a future
# release.
FirewallBackend=nftables

# FlushAllOnReload
# Flush all runtime rules on a reload. In previous releases some runtime
# configuration was retained during a reload, namely; interface to zone
# assignment, and direct rules. This was confusing to users. To get the old
# behavior set this to "no".
# Default: yes
FlushAllOnReload=yes

# ReloadPolicy
# Policy during reload. By default all traffic except for established
# connections is dropped while the rules are updated. Set to "DROP", "REJECT"
# or "ACCEPT". Alternatively, specify it per table, like
# "OUTPUT:ACCEPT,INPUT:DROP,FORWARD:REJECT".
# Default: ReloadPolicy=INPUT:DROP,FORWARD:DROP,OUTPUT:DROP
ReloadPolicy=INPUT:DROP,FORWARD:DROP,OUTPUT:DROP

# RFC3964_IPv4
# As per RFC 3964, filter IPv6 traffic with 6to4 destination addresses that
# correspond to IPv4 addresses that should not be routed over the public
# internet.
# Defaults to "yes".
RFC3964_IPv4=yes

# NftablesFlowtable
# This may improve forwarded traffic throughput by enabling nftables flowtable.
# It is a software fastpath and avoids calling nftables rule evaluation for
# data packets. This only works for TCP and UDP traffic.
# The value is a space separated list of interfaces.
# Example value "eth0 eth1".
# Defaults to "off".
NftablesFlowtable=off

# NftablesCounters
# If set to yes, add a counter to every nftables rule. This is useful for
# debugging and comes with a small performance cost.
# Defaults to "no".
NftablesCounters=no
```

**Comment by TorontoMedia** [comment]
You've enabled port 19105/tcp for both zone public and policy port-forwards, thus it never reaches the forward port rules.

**Comment by Silvigarabis** [comment]
> You've enabled port 19105/tcp for both zone public and policy port-forwards, thus it never reaches the forward port rules.

not sure if this is true, but I tested with following policy, without others (zone and policies) related to port 19105/tcp, and still not work…
```
port-forwards (active)
  priority: -1
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: ANY
  services:
  ports: 15537/tcp
  protocols:
  masquerade: yes
  forward-ports:
        port=19105:proto=tcp:toport=15537:toaddr=127.0.0.1
  source-ports:
  icmp-blocks:
  rich rules:
```
