### ISSUE TITLE
Docker compose services not reachable

### ISSUE THREAD

**Issue by Ragadabing** [firewalld/firewalld#416]
So I'm trying out the [Docker Compose Getting Started](https://docs.docker.com/compose/gettingstarted/) on a server running FirewallD as a firewall.

Basically I have this `docker-compose-yml` file:

```version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
``` 

When I disable firewall everything works, I can connect to the sample app via `localhost:5000`, but when I enable it nothing can connects to anything (probably the intended way).

I tried the following commands (without success):

```
firewall-cmd --permanent --zone=public --add-port=5000/tcp
firewall-cmd --add-forward-port=port=5000:proto=tcp:toport=5000:toaddr=0.0.0.0 --permanent --zone=public
```

So how do I configure FirewallD to achieve the following tasks?

1. Allow the port 5000 to be accessible globally (via `example.org:5000`?
2. Alllow the port 5000 to be accessible locally (via `localhost:5000`)?
2. Allow the web service to be able to see the redis service?

**Comment by Ragadabing** [comment]
Here's the output of `firewall-cmd --list-all`:

```
public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: dhcpv6-client https
  ports: 22/tcp 5000/tcp
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
        rule source ipset="sshguard4" drop
        rule family="ipv6" source ipset="sshguard6" drop             
        rule family="ipv4" source ipset="sshguard4" drop             
        rule source ipset="sshguard6" drop
```

And here of `docker ps`:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES                                                                             
77dffa2c02de        composetest_web     "python app.py"          23 hours ago        Up 10 seconds       0.0.0.0:5000->5000/tcp   composetest_web_1                                                                 
9fce85305ea7        redis:alpine        "docker-entrypoint.s…"   23 hours ago        Up 10 seconds       6379/tcp                 composetest_redis_1 
```
