### ISSUE TITLE
Interface assigned to zone is not listed

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [firewalld/firewalld#455]
Hi,
I'm using CentOS7 with firewalld-0.5.3-5.el7.noarch installed and I've found unexpected behavior of `firewall-cmd`

```
[root@puppet code]# /usr/bin/firewall-cmd --permanent --zone public --add-interface eth0
The interface is under control of NetworkManager and already bound to 'public'
The interface is under control of NetworkManager, setting zone to 'public'.
success
[root@puppet code]# /usr/bin/firewall-cmd --permanent --zone public --list-interfaces

[root@puppet code]# firewall-cmd --reload
success
[root@puppet code]# /usr/bin/firewall-cmd --permanent --zone public --list-interfaces

[root@puppet code]# 
```
But interface eth0 is listed in `firewall-cmd --list-all-zones`:
```
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
