### ISSUE TITLE
FirewallD doesn't go well with Docker

### ISSUE THREAD

**Issue by maverick85** [firewalld/firewalld#461]
Hi everybody,

I am an avid user of CentOS which ships firewalld since long.

So I've been using Docker fairly recently and yesterday I noticed firewalld rules are completely ignored by docker/docker containers. I found this funny cause on your Home page you read:

> Applications and libraries which support firewalld as a firewall management tool include:
> - NetworkManager
> - libvirt
> - docker
> - fail2ban

So basically I was setting up a server whose sole purpose is to run docker containers.
After setting things running, as I had a DB container running, I did the following:

```
firewall-cmd --permanent --new-zone=test-from-home && firewall-cmd --reload
firewall-cmd --permanent --zone=test-from-home --add-service=mysql
firewall-cmd --permanent --zone=test-from-home --add-source=XX.XX.XX.XX/32
firewall-cmd --reload
```
So then I went to testing, and I connected just fine. But then I logged in to another remote server, and I accessed the same when I totally should not.

These are outputs of my firewalld:
```
firewall-cmd --zone=test-from-home --list-all
test-from-home (active)
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: XX.XX.XX.XX/32
  services: mysql
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
```
firewall-cmd --zone=public --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: ssh dhcpv6-client
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules:
```
```
[root@nd01 latest]# firewall-cmd --get-active-zones
test-from-home
  sources: XX.XX.XX.XX/32
public
  interfaces: eth0
```
Also, I asked a friend to test using netcat, from yet another random location, and he manages to connect too...

## FirewallD doesn't play nice with Docker (or vice-versa)

Meanwhile I came across the fact that FirewallD and Docker do not play along.
According to the Docker documentation, the way to circumvent this is by disabling IPTables:
- [Docker and iptables](https://docs.docker.com/network/iptables/)

As it says from the very first stance:
> On Linux, Docker manipulates `iptables` rules to provide network isolation. This is an implementation detail, and you should not modify the rules Docker inserts into your `iptables` policies.

Which wouldn't be my first resort as adviced against.

So I don't get how we go from this to firewalld friendly, but I would enjoy learning.
Anyway, this page goes on about how to fix it, and I actually took a few ideas from another blog post I came across [Docker meets firewall - finally an answer](http://bit.ly/2SNpMuV) and set it up.

But as firewalld gets more and more audience, I think it would be useful if someone:

a) fix where it says firewalld works with docker...
b) make firewalld play nice with docker?
maybe by adding a plugin for docker that would allow to move on the DOCKER-USER chain?

```
CentOS 7 minimal-install;
Docker version 18.09.2, build 6247962
```
