### ISSUE TITLE
firewalld 0.6.4 / iptables: multicast mdns packets blocked even if enabled

### ISSUE THREAD

**Issue by mwilck** [firewalld/firewalld#497]
I see blocked multicast mdns packets:

```
Jul 06 00:16:58 apollon.suse.de kernel: FINAL_REJECT: IN=wired1 OUT= MAC=01:00:5e:00:00:fb:54:a0:50:d8:bc:e8:08:00 SRC=192.168.1.1 DST=224.0.0.251 LEN=32 TOS=0x00 PREC=0xC0 TTL=1 ID=0 DF PROTO=2
```
... even  though mdns traffic should be allowed on interface "wired1":
```
# firewall-cmd --zone=home  --list-all
home (active)
  target: default
  icmp-block-inversion: no
  interfaces: wired1
  sources: 
  services: dhcp dhcpv6-client dns mdns nfs nfs3 samba-client ssh synergy
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

`iptables-save` prints this resulting rule for mdns:
```
-A IN_home_allow -d 224.0.0.251/32 -p udp -m udp --dport 5353 -m conntrack --ctstate NEW,UNTRACKED -j ACCEPT
```

Apparently the port number and possibly also the "conntrack" and "ctstate" fields cause the rule not to match actual mdns traffic.

Currently I work around this issue with
```
        rule family="ipv4" destination address="224.0.0.0/24" accept
        rule family="ipv4" port port="5353" protocol="udp" accept
```
Given the contents of `mdns.xml`:
```
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>Multicast DNS (mDNS)</short>
  <port protocol="udp" port="5353"/>
  <destination ipv4="224.0.0.251" ipv6="ff02::fb"/>
</service>
```
firewalld seems to use a logical "AND" between the address and port, where here, "OR" would be more appropriate.
