### ISSUE TITLE
Enhancement: firewall-cmd output should take into account --timeout settings

### ISSUE THREAD

**Issue by garrymar** [firewalld/firewalld#651]
Dear Developers,

I found that firewall-cmd does not provide any information with regard to applied --timeout settings. I believe it can make a troubleshooting process a tricky one. For example, a "--list-all" output for a default zone with a temporary added telnet service (firewall-cmd --add-service=telnet --timeout=5m) could look like this:

```
# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: dhcpv6-client ssh telnet (75 seconds left)
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules:
```

Many thanks in advance!
