### ISSUE TITLE
The output of a blank firewall-cmd could be more useful

### ISSUE THREAD

**Issue by nullr0ute** [firewalld/firewalld#808]
**What would you like to be added**:
The output of a blank firewall-cmd could be more useful

**Why is this needed**:

When you run "firewall-cmd" it could be more useful. Currently it outputs the following:
````
# firewall-cmd 
usage: see firewall-cmd man page
No option specified.
````

But not all systems install the man pages, such as platforms based on ostree, so the output from "man firewall-cmd" produces nothing but if you run "firewall-cmd --help" you get vast arrays of useful information but there is no mention of that in the output. So it could mention both the man page and --help as an option.

BUT it could be *even* more useful by outputting a summary of it's status like whether it's running, the current backend in use, current zone, whether it's in lockdown, and then listing the man page and --help options.

**Comment by erig0** [comment]
@BrennanPaciorek, I think this should report firewalld's `--state` and suggest using `--help`.
e.g.
```
# firewall-cmd
firewalld state: RUNNING

No option specified.
For usage see `firewall-cmd --help` and man page firewall-cmd(1).
```

@todoleza, any thoughts on this? What would be useful to show?

**Comment by todoleza** [comment]
Improving the default message is a great idea! I support moderate extension of the output.
Currently the message says little to nothing but informs that "some" options should be specified and then exits with non-zero non-defined exit code (It's been value of 2 since beginning IIRC).

I went a little ahead and tried to compile sample output of what I would consider useful.
```
## --state
RUNNING
## --get-active-zones
public
  interfaces: enp9s0u2u1u2 wlp0s20f3 tun0 enp47s0u2u1u2
## --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp47s0u2u1u2 enp9s0u2u1u2 tun0 wlp0s20f3
  sources:
  services: dhcpv6-client mdns ssh
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
	rule family="ipv4" source address="192.168.0.0/20" service name="kdeconnect" accept

BEWARE: showing only default zone with up to 10 rich rules listed.

Do NOT screenscrape this summary, we don't consider its output stable.

No option specified!
Use firewall-cmd --help to see usage or firewall-cmd(1) manpage.
```
I think that the exit status should be kept since this is non-standard and not-scriptable use for other use than typing into CLI.

The warnings were inspired by [iw](https://wireless.wiki.kernel.org/en/users/Documentation/iw).
