### ISSUE TITLE
adding dns service only allows IPv6

### ISSUE THREAD

**Issue by brianjmurrell** [firewalld/firewalld#882]
**What happened**:
I added the _dns_ service to firewalld.  It only allowed IPv6 traffic in but not IPv4.  I have to add manual iptables rules to allow IPv4 queries.

**What you expected to happen**:
Adding the dns service should allow both IPv4 and IPv6 dns queries to be accepted.

**How to reproduce it (as minimally and precisely as possible)**:
```
# firewall-cmd --add-service dns
```
Try to query from external to the machine on both it's IPv4 and IPv6 addresses.

**Anything else we need to know?**:
When trying to query to the IPv4 address fails, I can simply do:
```
$ sudo iptables -I INPUT -p tcp --dport 53 -j ACCEPT
$ sudo iptables -I INPUT -p udp --dport 53 -j ACCEPT
```
to allow external queries.

**Environment**:
- Firewalld Version: `firewalld-0.8.2-7.el8_4.noarch`
- Firewalld Backend: `FirewallBackend=nftables`
- OS: CentOS 8.4.2105
- Others:
Host is a cloud VM.  As is typical for such, the actual host has an RFC-1918 address which is NATted to an external address.  Although this is not at all unlike any host on an IPv4 Internet connection that only has a single address and NATs to an RFC-1918 network through a router so I can't imagine there is anything strange going on in that regard.

Surely there is more information I could provide.  In fact if this were using `iptables` there is a ton of information I could provide, but I have not done much with nftables yet so don't really know how or what information to gather, or how to read the output from the `nft` tool.  I am happy of course to provide whatever else you need.

**Comment by erig0** [comment]
> It only allowed IPv6 traffic in but not IPv4. I have to add manual iptables rules to allow IPv4 queries.

How did you verify this?

Can you also share you firewalld config? `firewall-cmd --list-all-zones`

**Comment by brianjmurrell** [comment]
> How did you verify this?

By using a DNS querying tool, such as `dig` on another machine.
 
> Can you also share you firewalld config? `firewall-cmd --list-all-zones`

```
block
  target: %%REJECT%%
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

dmz
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

drop
  target: DROP
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

external
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: ssh
  ports: 
  protocols: 
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

home
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: cockpit dhcpv6-client mdns samba-client ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

internal
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: cockpit dhcpv6-client mdns samba-client ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

nm-shared
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcp dns ssh
  ports: 
  protocols: icmp ipv6-icmp
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule priority="32767" reject

public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens3
  sources: 
  services: cockpit dhcpv6-client dns ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

trusted
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

work
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: cockpit dhcpv6-client ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
