### ISSUE TITLE
How to masquerade from an ingress zone that has a target=DROP ?

### ISSUE THREAD

**Issue by jagaudet** [firewalld/firewalld#939]
I have two zones set up similar to:
```
root@host:~# firewall-cmd --zone=external --list-all
external (active)
  target: DROP
  icmp-block-inversion: no
  interfaces: eth1
  sources: 
  services: 
  ports: 
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule family="ipv4" source address="192.168.8.0/24" masquerade
	rule family="ipv4" source address="192.168.56.0/24" masquerade

root@host:~# firewall-cmd --zone=internal --list-all
internal (active)
  target: DROP
  icmp-block-inversion: no
  interfaces: eth0 wlan0
  sources: 
  services: ssh
  ports: 
  protocols: icmp
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
The "masquerade" rich rules on "internal" result in these rules in the nftables backend (the egress zone's "forward out allow" chain):
```
        chain filter_FWDO_external_allow {
                ip saddr 192.168.8.0/24 ct state { new, untracked } accept
                ip saddr 192.168.56.0/24 ct state { new, untracked } accept
        }
```
However, the DROP target for "internal" results in (the ingress zone's "forward in" chains):
```
        chain filter_FWDI_internal {
                jump filter_FWDI_internal_pre
                jump filter_FWDI_internal_log
                jump filter_FWDI_internal_deny
                jump filter_FWDI_internal_allow
                jump filter_FWDI_internal_post
                drop
        }

        chain filter_FWDI_internal_pre {
        }

        chain filter_FWDI_internal_log {
        }

        chain filter_FWDI_internal_deny {
        }

        chain filter_FWDI_internal_allow {
        }

        chain filter_FWDI_internal_post {
        }
```
As opposed to a "default" target, which yields:
```
        chain filter_FWDI_internal {
                jump filter_FWDI_internal_pre
                jump filter_FWDI_internal_log
                jump filter_FWDI_internal_deny
                jump filter_FWDI_internal_allow
                jump filter_FWDI_internal_post
                meta l4proto { icmp, ipv6-icmp } accept
        }
```

Because the filter_FORWARD_IN_ZONES are processed before the filter_FORWARD_OUT_ZONES, that "drop" means we never get to the point where we evaluate the added "accept".

I can work around this by manually adding a rule to filter_FWDI_internal_allow using "nft", but that's pretty dirty.  I tried using the direct interface, but, since that uses iptables, I can't add a useful "allow", as the nftables "deny" is still involved.

The only solution I can come up with is to switch to the iptables back end, and add a direct rule.  Am I missing something more elegant?  I suppose I could leave the target as "default" and direct rule "drop" for INPUT and OUTPUT, but that's still an "iptables" solution (and seems less elegant); will we eventually have native nftables direct rules we can use here?

High level, it seems like "masquerade" should allow an option to specify the source zone, so we can automatically add an "accept" rule to that zone's FWDI chains.  Alternately, we could add the existing "source based" rule to the FWDI chain for all other zones, so masquerading works "out of the box"; that forwarding requires "default" to use the egress zone's rule is documented, but that firewalld won't automatically set up ingress zone rules to allow forwarding for "masquerade" is less clear.

Or, maybe, for each zone, instead of just "forward", we have "forward from" and "forward to"; at that point, adding "masquerade" to the egress zone, and "forward from" to the ingress zone, would be expected to work.

Finally, having different "target" policies for FORWARD_IN, FORWARD_OUT, INPUT and OUTPUT seems like a potentially reasonable product solution.  I don't want to have to use "default" for INPUT, as I prefer DROP to REJECT, but it appears the only way to do that impacts "FORWARD_IN", which seems too limited; I'm fine with "default" for FORWARD_IN, as we still have the egress zone's rules to traverse.  "Masquerade from" would also work here.

If there are no product fix options available to automate this, maybe emitting a warning at configure/load time for each "target=DROP" potential ingress zone, indicating that it won't allow masquerading, may be in order, should masquerading be enabled for a zone.
