### ISSUE TITLE
[Question] NAT policy objects for XFRM policies

### ISSUE THREAD

**Issue by Unb0rn** [firewalld/firewalld#956]
Hello! I'm trying to set up an IPSec (strongswan) VPN gateway with IKEv2. I am able to establish SAs but I'm unable to NAT this traffic outside through `eth0` in `public` zone.
Previously all I had to do was just to enable masquerade in public zone `firewall-cmd --zone=public` but after policy objects were introduced I have no ideas what policy should I define (as there is no interface for ingress, obviously)

At the same time I have another VPN protocol-Wireguard through `wg0` interface and I had no problems creating policy (and enabling NAT) for it. Something like:
```
firewall-cmd --new-policy NAT_int_to_ext --permanent
firewall-cmd --policy NAT_int_to_ext --permanent --add-ingress-zone internal
firewall-cmd --policy NAT_int_to_ext --permanent --add-egress-zone public
firewall-cmd --policy NAT_int_to_ext --permanent --set-target ACCEPT
```
So all the traffic from `internal` zone with `wg0` to `public` zone `eth0` will pass through `ACCEPT` rule. And `public` zone has masquerading rule enabled.
But how do I define something like this for XFRM rules? I will connect with Road Warrior setup so I don't know my remote IP to add it to some new zone with source...
Thanks!

**Comment by erig0** [comment]
Can you describe the setup more? I'm not very familiar with IPSec and it's myriad of operating modes.

There is an RFE for ipsec matching, see #680.

**Comment by Unb0rn** [comment]
Well I have a VPC running Ubuntu 22.04 which has firewalld 1.1.1.
It's main purpose is VPN gateway mainly with two protocols - Wireguard and IPSec(strongSwan). Wireguard has wg0 interface and IPSec runs in two different ways. First there is a gre1 interface with IPSec rule - my remote MikrtoTik router's traffic is routed through it.  Second, there are IPSec rules without any interface that generate XFRM rules when the client connects.
This VPS has a publicly routable ipv4 address as well as several ipv6 addresses on eth0.
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:16:2e:16:d3:55 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    inet 46.22.211.85/24 brd 46.22.211.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 2a01:97a0:8:204::a1/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 2a01:97a0:8:204::a0/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::56:4233:b832:a8b7/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: cni-podman0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 3a:ed:99:0d:61:ba brd ff:ff:ff:ff:ff:ff
    inet 10.88.0.1/16 brd 10.88.255.255 scope global cni-podman0
       valid_lft forever preferred_lft forever
    inet6 fe80::38ed:99ff:fe0d:61ba/64 scope link 
       valid_lft forever preferred_lft forever
5: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
6: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
7: erspan0@NONE: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
8: gre1@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1435 qdisc noqueue state UNKNOWN group default qlen 1000
    link/gre 46.22.211.85 peer 195.160.246.139
    inet 192.168.1.0/31 scope global noprefixroute gre1
       valid_lft forever preferred_lft forever
    inet6 fe80::6be3:1702:6b69:d60b/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
9: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 172.20.10.1/24 scope global wg0
       valid_lft forever preferred_lft forever
    inet6 fdbc:1be5:fd3c::1/64 scope global 
       valid_lft forever preferred_lft forever
```
Firewalld uses mainly 3 zones, public, internal and trusted with wg0 and gre1 being in internal and eth0 in public and public zone has masquerading enabled:

> firewall-cmd --zone=public --list-all

```
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: dhcpv6-client gre http https i2p ipsec l2tp shadowsocks ssh wireguard
  ports: 
  protocols: 
  forward: no
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: echo-request
  rich rules:
```

> firewall-cmd --zone=internal --list-all

```
internal (active)
  target: default
  icmp-block-inversion: no
  interfaces: gre1 wg0
  sources: 
  services: dhcpv6-client mdns samba-client ssh
  ports: 
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
After upgrading past firewalld 1.0 to route VPN client's traffic through eth0 I had to create additional policy, allowing traffic from internal (wgo and gre1) zone to eth0 (masqueraded default route):

> firewall-cmd --get-policies
`NAT_int_to_ext allow-host-ipv6`

> firewall-cmd --info-policy NAT_int_to_ext
```
NAT_int_to_ext (active)
  priority: -1
  target: ACCEPT
  ingress-zones: internal
  egress-zones: public
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
It was fairly simple and Wireguard clients on wg0 and MikroTik router on gre1 with IPsec became able to route their traffic through this VPS.
Now for the part I don't get how to make it work.
As there is no internal interface for XFRM-only IPSec to add it to internal zone, how can I allow all the traffic from all the "road warrior" clients in firewalld? Maybe some additional policy or some other way to add IPSec clients to the internal zone?
